elasticsearch:
  build: ./docker/elasticsearch/
  ports: 
    - "9200:9200"
  expose:
    - 9200

project-crawler:
  build: ./docker/project-crawler/.
  ports: 
    - "8666:8666"
  links:
    - elasticsearch
  volumes:
    # Mounting configfile of Project-Crawler
    - ./config/project-crawler/:/opt/project-crawler/src/app/config/


project-display:
  build: ./docker/project-display/.
  ports: 
    - "80:80"
  expose:
    - "80"
  links:
    - elasticsearch
    - project-crawler
  volumes:
    # Mounting configfile of Project-Crawler
    - ./config/project-display/:/var/www/config/



