store:
  build: ./docker/virtuoso/
  expose: 
    - 8890
    - 1111
  environment:
    PWDDBA: "MuZ4eed1quu8waes"
  volumes:
    - ./data/virtuoso/:/var/lib/virtuoso/db/

presentation:
  build: ./docker/ontowiki/
  links:
    - store
  ports:
    - 8080:80
  volumes:
    - ./config/ontowiki/:/config/

vocto:
  build: ./docker/vocto/
  ports:
    - 8081:80
  volumes:
    - ./config/vocto/:/config/
    - ./data/vocto/:/var/www/data/

elasticsearch:
  build: ./docker/elasticsearch/
  ports: 
    - "9200:9200"
  expose:
    - 9200

project-crawler:
  build: ./docker/project-crawler/.
  ports:
    - "8666:8666"
  links:
    - elasticsearch
  volumes:
    # Mounting configfile of Project-Crawler
    - ./config/project-crawler/:/opt/project-crawler/src/app/config/

project-display:
  build: ./docker/project-display/.
  ports: 
    - "8087:80"
  expose:
    - "80"
  links:
    - elasticsearch
    - project-crawler
  volumes:
    - ./config/project-display/:/var/www/config/
