virtuoso:
  build: ./docker/virtuoso/
  restart: always
  ports:
    - 8890:8890
    - 1111:1111
  environment:
    PWDDBA: "dba"
  volumes:
    - ./data/virtuoso/:/var/lib/virtuoso/db/

ontowiki:
  build: ./docker/ontowiki/
  restart: always
  links:
    - virtuoso
  ports:
    - 8080:80
  volumes:
    - ./config/ontowiki/:/config/

vocto:
  build: ./docker/vocto/
  restart: always
  ports:
    - 8081:80
  volumes:
    - ./config/vocto/:/config/
    - ./data/vocto/:/var/www/data/

webserver:
  build: ./docker/webserver/
  ports:
    - 8082:80
    - 8083:81
  volumes:
    - ./config/webserver/:/config/
    - ./data/webserver/www/:/var/www/


elasticsearch:
  build: ./docker/elasticsearch/
  ports: 
    - "9200:9200"
  expose:
    - 9200

project-crawler:
  build: ./docker/project-crawler/.
  links:
    - elasticsearch


proxy:
  image: nginx:1.9
  restart: always
  ports:
    - 80:80
    - 443:443
  restart: always
  mem_limit: 500MB
  volumes:
    - ./data/proxy/nginx.conf:/etc/nginx/nginx.conf:rw
    - ./data/proxy/ssl/:/etc/nginx/ssl/:rw
    - ./data/proxy/conf.d/:/etc/nginx/conf.d/:rw
    - ./data/proxy/log/:/var/log/nginx/:rw
  links:
    - vocto
    - ontowiki
    - webserver

